version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '8000:8000'
    volumes:
      - .:/opt/app/api

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root_password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    # expose:
    #   # Opens port 3306 on the container
    #   - '3306'
    #   # Where our data will be persisted
    volumes:
      - docker:/var/lib/mysql
volumes:
  docker: